enable: "etcd"
etcd:
  rootDirectory: openim
  address: [ 47.108.26.241:12379 ]
  username: ''
  password: ''

zookeeper:
  schema: openim
  address: [ 47.108.26.241:12181 ]
  username: ''
  password: ''

