enable: "etcd"
etcd:
  rootDirectory: openim
  address: [ 121.43.227.78:12379 ]
  username: 'root'
  password: 'lihuaOpenIM123'

zookeeper:
  schema: openim
  address: [ 0.0.0.0:12181 ]
  username: ''
  password: ''

