# URI for database connection, leave empty if using address and credential settings directly
uri: ''
# List of MongoDB server addresses
address: [ 121.43.227.78:27017 ]
# Name of the database
database: openim_v3
# Username for database authentication
username: lihuaOpenIM
# Password for database authentication
password: lihuaOpenIM123
# Maximum number of connections in the connection pool
maxPoolSize: 100
# Maximum number of retry attempts for a failed database connection
maxRetry: 10
